name: m8131a

instrument:
  visa_sim: mock/visa/digitizer/ks_m8131a.yml
  address: TCPIP0::1.2.3.4::INSTR

topics:
  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    instrument_command: '{:}'
    type: set

  clock_src:
    description: Sets the source of the reference frequency
    signature: [[str], None]
    instrument_command: ':TIMebase:REFClock {:}'
    type: set

  query_clock_src:
    description: Query the source of the reference frequency
    signature: [[], str]
    instrument_command: ':TIMebase:REFClock?'
    type: get

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  raw_query:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    # Set parameter description.
    description: Raw query to intrument

    # Parameter setter configuration.
    set:
      signature:
        - raw_query:
            type: str
      instrument_command:
        - query: '{:}'

    # Parameter getter configuration.
    get:

  idn:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'