name: m8131a
visa-sim: mock/visa/digitizer/ks_m8131a.yml
address: TCPIP0::1.2.3.4::INSTR

topics:
  connect:
    description: Establish Connection with Digitizer

  disconnect:
    description: Close connection with Digitizer

  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  clock_src:
    description: Sets the source of the reference frequency
    signature: [[str], None]
    command: ':TIMebase:REFClock {:}'

  tc_query_raw:
    description: Perform msg query to the instrument
    signature: [[str], str]
    command: '{:}'

  query_idn:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  query_clock_src:
    description: Query the source of the reference frequency
    signature: [[], str]
    command: ':TIMebase:REFClock?'

  tm_query_raw:
    description: Retrieve the value of the last msg query
    signature: [[], str]
    command: '{:}'

  query_connected:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: 0
    setter:
      connect:
      disconnect:
    getter:
      query_connected:

  query_raw_result:
    default: ''
    setter:
      tc_query_raw:
    getter:
      tm_query_raw: