name: m8131a

instrument:
  visa_sim: mock/visa/digitizer/ks_m8131a.yml
  address: TCPIP0::1.2.3.4::INSTR

topics:
  connect:
    description: Establish Connection with Digitizer
    type: set

  disconnect:
    description: Close connection with Digitizer
    type: set

  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'
    type: set

  clock_src:
    description: Sets the source of the reference frequency
    signature: [[str], None]
    command: ':TIMebase:REFClock {:}'
    type: set

  tc_query_raw:
    description: Perform msg query to the instrument
    signature: [[str], str]
    command: '{:}'
    type: set

  query_idn:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'
    type: get

  query_clock_src:
    description: Query the source of the reference frequency
    signature: [[], str]
    command: ':TIMebase:REFClock?'
    type: get

  tm_query_raw:
    description: Retrieve the value of the last msg query
    signature: [[], str]
    command: '{:}'
    type: get

  query_connected:
    description: Query the connection status to the instrument
    signature: [[], bool]
    type: get

parameters:
  connected:
    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    setter:
      connect:
      disconnect:
    getter:
      query_connected:

  query_raw_result:
    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    setter:
      tc_query_raw:
    getter:
      tm_query_raw: