name: Keysight Z2091C Smart Switch Matrix Controller
version: 0.1
status: Partial interface implementation
maintainer: Mamba Developers
maintainer_email: mambaframework@gmail.com

instrument:
  visa_sim: mock/visa/switch_matrix/ks_z2091c.yml
  address: TCPIP0::1.2.3.4::INSTR

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  raw_query:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    # Set parameter description.
    description: Raw query to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_query: {type: str}]
      instrument_command:
        - query: '{:}'

    # Parameter getter configuration.
    get:

  raw_write:
    # Set parameter description.
    description: Raw write to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_write: {type: str}]
      instrument_command: [write: '{:}']

  idn:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'

  clear:
    # Set parameter description.
    description: Clear status

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*CLS']

  reset:
    # Set parameter description.
    description: Reset

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*RST']

  sys_err:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Oldest error in queue

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SYST:ERR?'

  opc:
    # Set parameter type.
    type: int

    # Set parameter description.
    description: Returns "1" at the completion of the current operation

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*OPC?'

  route_close_set:
    # Set parameter description.
    description: Close specified channels

    # Parameter setter configuration.
    set:
      signature: [elem_list: {type: str}]
      instrument_command: [write: 'ROUTe:CLOSe (@{:})']

  route_close_get:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Query specified channels close state

    # Parameter setter configuration.
    set:
      signature: [elem_list: {type: str}]
      instrument_command: [query: 'ROUTe:CLOSe? (@{:})']

    # Parameter getter configuration.
    get:

  path_catalog:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: List of user-defined path names currently stored in non-volatile memory.

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'ROUTe:PATH:CATalog?'

  path_delete:
    # Set parameter description.
    description: Remove path by name

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}]
      instrument_command: [write: 'ROUT:PATH:DEL {:}']

  path_define_set:
    # Set parameter description.
    description: Define a named path

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}, elem_list: {type: str}]
      instrument_command: [write: 'ROUTe:PATH:DEFine {0}, (@{1})']

  path_define_get:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Query defined named path

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}]
      instrument_command: [query: 'ROUTe:PATH:DEFine? {:}']

    # Parameter getter configuration.
    get: