#############################################################################
##
## Copyright (C) 2020 The Mamba Company.
## Contact: themambacompany@gmail.com
##
## This file is part of Mamba Server.
##
## $MAMBA_BEGIN_LICENSE:LGPL$
## Commercial License Usage
## Licensees holding valid commercial Mamba licenses may use this file in
## accordance with the commercial license agreement provided with the
## Software or, alternatively, in accordance with the terms contained in
## a written agreement between you and The Mamba Company. For licensing terms
## and conditions see LICENSE. For further information contact us at
## themambacompany@gmail.com.
##
## GNU Lesser General Public License Usage
## Alternatively, this file may be used under the terms of the GNU Lesser
## General Public License version 3 as published by the Free Software
## Foundation and appearing in the file LICENSE.LGPL3 included in the
## packaging of this file. Please review the following information to
## ensure the GNU Lesser General Public License version 3 requirements
## will be met: https://www.gnu.org/licenses/lgpl-3.0.html.
##
## GNU General Public License Usage
## Alternatively, this file may be used under the terms of the GNU
## General Public License version 2.0 or (at your option) the GNU General
## Public license version 3 or any later version approved by the KDE Free
## Qt Foundation. The licenses are as published by the Free Software
## Foundation and appearing in the file LICENSE.GPL2 and LICENSE.GPL3
## included in the packaging of this file. Please review the following
## information to ensure the GNU General Public License requirements will
## be met: https://www.gnu.org/licenses/gpl-2.0.html and
## https://www.gnu.org/licenses/gpl-3.0.html.
##
## $MAMBA_END_LICENSE$
##
#############################################################################

name: Keysight Z2091C Smart Switch Matrix Controller
version: 0.1
status: Partial interface implementation
maintainer: Mamba Developers
maintainer_email: mambaframework@gmail.com

instrument:
  visa_sim: mock/visa/switch_matrix/ks_z2091c.yml
  address: TCPIP0::1.2.3.4::INSTR

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  raw_query:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    # Set parameter description.
    description: Raw query to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_query: {type: str}]
      instrument_command:
        - query: '{:}'

    # Parameter getter configuration.
    get:

  raw_write:
    # Set parameter description.
    description: Raw write to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_write: {type: str}]
      instrument_command: [write: '{:}']

  idn:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'

  clear:
    # Set parameter description.
    description: Clear status

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*CLS']

  reset:
    # Set parameter description.
    description: Reset

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*RST']

  sys_err:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Oldest error in queue

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SYST:ERR?'

  opc:
    # Set parameter type.
    type: int

    # Set parameter description.
    description: Returns "1" at the completion of the current operation

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*OPC?'

  route_close_set:
    # Set parameter description.
    description: Close specified channels

    # Parameter setter configuration.
    set:
      signature: [elem_list: {type: str}]
      instrument_command: [write: 'ROUTe:CLOSe (@{:})']

  route_close_get:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Query specified channels close state

    # Parameter setter configuration.
    set:
      signature: [elem_list: {type: str}]
      instrument_command: [query: 'ROUTe:CLOSe? (@{:})']

    # Parameter getter configuration.
    get:

  path_catalog:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: List of user-defined path names currently stored in non-volatile memory.

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'ROUTe:PATH:CATalog?'

  path_delete:
    # Set parameter description.
    description: Remove path by name

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}]
      instrument_command: [write: 'ROUT:PATH:DEL {:}']

  path_define_set:
    # Set parameter description.
    description: Define a named path

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}, elem_list: {type: str}]
      instrument_command: [write: 'ROUTe:PATH:DEFine {0}, (@{1})']

  path_define_get:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Query defined named path

    # Parameter setter configuration.
    set:
      signature: [name: {type: str}]
      instrument_command: [query: 'ROUTe:PATH:DEFine? {:}']

    # Parameter getter configuration.
    get: