sudo: false

language:
  - python

services:
  - xvfb

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pycodestyle barracuda
  - pytest --cov-config=.coveragerc --cov=barracuda --verbose --capture=no tests
  - pip install .

after_success:
  - codecov

notifications:
  email: false
