sudo: false

language:
  - python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install -U codecov pytest-cov

script:
  - pycodestyle mamba_controller
  - pytest --cov=./ --verbose --capture=no mamba_controller
  - pip install .

after_success:
  - codecov

notifications:
  email: false
