sudo: false

language:
  - python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - pycodestyle mamba_controller
  - pytest --verbose --capture=no mamba_controller
  - pip install .

notifications:
  email: false
