sudo: false

language:
  - python

services:
  - xvfb

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pycodestyle mamba_controller
  - pytest --cov-config=.coveragerc --cov=mamba_controller --verbose --capture=no tests
  - pip install .

after_success:
  - codecov

notifications:
  email: false
