################################################################################################
##
##  Copyright (c) Mamba Developers. All rights reserved.
##  Licensed under the MIT License. See License.txt in the project root for license information.
##
################################################################################################

name: Component  # Name of the action
menu: '&Plugins'  # High level Menu name shown in the menu bar
shortcut: Ctrl+C # Menu shortcut (Optional)