name: tcp_socket_controller
address: 0.0.0.0
tc_port: 8081
tm_port: 8082

eom:
  TCPIP INSTR:
    q: "\r\n"
    r: "\n"

topics:
  TCP_SOCKET_CONTROLLER_CONNECT:
    key: '@connect'
    description: Establish Connection with remote cyclic tm server

  TCP_SOCKET_CONTROLLER_DISCONNECT:
    key: '@disconnect'
    description: Close connection with remote cyclic tm  server

  TCP_SOCKET_CONTROLLER_TC_TM_1:
    description: Send a tm_1 set value
    signature: [[str], None]
    command: 'tm_1 {:}'

  TCP_SOCKET_CONTROLLER_TC_TM_2:
    description: Send a tm_1 set value
    signature: [[str], None]
    command: 'tm_2 {:}'

  TCP_SOCKET_CONTROLLER_TC_TM_3:
    description: Send a tm_1 set value
    signature: [[str], None]
    command: 'tm_3 {:}'

  TCP_SOCKET_CONTROLLER_TM_TM_1:
    description: Query the source of the reference frequency
    signature: [[], str]

  TCP_SOCKET_CONTROLLER_TM_TM_2:
    description: Query the source of the reference frequency
    signature: [[], str]

  TCP_SOCKET_CONTROLLER_TM_TM_3:
    description: Query the source of the reference frequency
    signature: [[], str]

  TCP_SOCKET_CONTROLLER_QUERY_CONNECTED:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: false
    setter:
      TCP_SOCKET_CONTROLLER_CONNECT:
      TCP_SOCKET_CONTROLLER_DISCONNECT:
    getter:
      TCP_SOCKET_CONTROLLER_QUERY_CONNECTED:

  tm_1:
    default: ''
    setter:
      TCP_SOCKET_CONTROLLER_TC_TM_1:
    getter:
      TCP_SOCKET_CONTROLLER_TM_TM_1:

  tm_2:
    default: ''
    setter:
      TCP_SOCKET_CONTROLLER_TC_TM_2:
    getter:
      TCP_SOCKET_CONTROLLER_TM_TM_2:

  tm_3:
    default: ''
    setter:
      TCP_SOCKET_CONTROLLER_TC_TM_3:
    getter:
      TCP_SOCKET_CONTROLLER_TM_TM_3: