name: RS SMB100b Signal Gen
visa-sim: mock/visa/signal_generator/rs_smb100b.yml
address: TCPIP0::1.2.3.4::INSTR

topics:
  connect:
    description: Establish Connection with SMB

  disconnect:
    description: Close connection with SMB

  rst:
    description: Clear the output buffer
    command: '*CLS'

  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  freq_mode:
    description: Set the frequency mode for generating the RF output signal
    signature: [[str], None]
    command: 'FREQuency:MODE {:}'

  out_power:
    description: Set the RF output signal
    signature: [[str], None]
    command: 'OUTP {:}'

  cw_freq:
    description: Sets the frequency of the RF output signal
    signature: [[int], None]
    command: 'FREQuency:CW {:}'

  clock_src:
    description: Sets the source of the reference frequency
    signature: [[str], None]
    command: 'SOURce:ROSCillator:SOURce {:}'

  power_level:
    description: Sets the RF level applied to the device under tests
    signature: [[float], None]
    command: 'POWer {:}'

  tc_query_raw:
    description: Perform msg query to the instrument
    signature: [[str], str]
    command: '{:}'

  query_idn:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  query_out_power:
    description: Query the RF output signal
    signature: [[], int]
    command: 'OUTP?'

  query_freq_mode:
    description: Query the frequency mode for generating the RF output signal
    signature: [[], str]
    command: 'FREQuency:MODE?'

  query_cw_freq:
    description: Query the frequency of the RF output signal
    signature: [[], int]
    command: 'FREQuency:CW?'

  query_clock_src:
    description: Query the source of the reference frequency
    signature: [[], str]
    command: 'SOURce:ROSCillator:SOURce?'

  query_power_level:
    description: Query the RF level applied to the device under tests
    signature: [[], float]
    command: 'POWer?'

  query_sys_err:
    description: Query the error queue for the oldest item and removes it from the queue
    signature: [[], str]
    command: 'SYST:ERR?'

  tm_query_raw:
    description: Retrieve the value of the last msg query
    signature: [[], str]
    command: '{:}'

  query_connected:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: 0
    setter:
      connect:
      disconnect:
    getter:
      query_connected:

  query_raw_result:
    default: ''
    setter:
      tc_query_raw:
    getter:
      tm_query_raw: