############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

name: Quit  # Name of the action
menu: File  # High level Menu name shown in the menu bar
status_tip: Close Mamba Server # Message shown in the status bar (Optional)
shortcut: Ctrl+Q # Menu shortcut (Optional)