#############################################################################
##
## Copyright (C) 2020 The Mamba Company.
## Contact: themambacompany@gmail.com
##
## This file is part of Mamba Server.
##
## $MAMBA_BEGIN_LICENSE:LGPL$
## Commercial License Usage
## Licensees holding valid commercial Mamba licenses may use this file in
## accordance with the commercial license agreement provided with the
## Software or, alternatively, in accordance with the terms contained in
## a written agreement between you and The Mamba Company. For licensing terms
## and conditions see LICENSE. For further information contact us at
## themambacompany@gmail.com.
##
## GNU Lesser General Public License Usage
## Alternatively, this file may be used under the terms of the GNU Lesser
## General Public License version 3 as published by the Free Software
## Foundation and appearing in the file LICENSE.LGPL3 included in the
## packaging of this file. Please review the following information to
## ensure the GNU Lesser General Public License version 3 requirements
## will be met: https://www.gnu.org/licenses/lgpl-3.0.html.
##
## GNU General Public License Usage
## Alternatively, this file may be used under the terms of the GNU
## General Public License version 2.0 or (at your option) the GNU General
## Public license version 3 or any later version approved by the KDE Free
## Qt Foundation. The licenses are as published by the Free Software
## Foundation and appearing in the file LICENSE.GPL2 and LICENSE.GPL3
## included in the packaging of this file. Please review the following
## information to ensure the GNU General Public License requirements will
## be met: https://www.gnu.org/licenses/gpl-2.0.html and
## https://www.gnu.org/licenses/gpl-3.0.html.
##
## $MAMBA_END_LICENSE$
##
#############################################################################

name: Single Port TCP Server Mock

# Component network configuration

instrument:
  address: 0.0.0.0
  port: 8085
  encoding: utf-8
  terminator:
    write: "\n"
    read: "\r\n"

# Component TMTC

parameters:
  idn:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: 'Mamba Framework,Single Port TCP Mock,1.0'

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'

  syst_err:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '0,_No_Error'

    # Set parameter description.
    description: Oldest error in queue

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SYST:ERR?'

  cls:
    # Set parameter description.
    description: Clear status

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*CLS']

  parameter_1:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 1

    # Parameter setter configuration.
    set:
      signature: [value: {type: int}]
      instrument_command:
        - query: 'PARAMETER_1 {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'PARAMETER_1?'

  parameter_2:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '2'

    # Parameter setter configuration.
    set:
      signature: [value: {type: str}]
      instrument_command:
        - query: 'PARAMETER_2 {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'PARAMETER_2?'

  parameter_3:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 3

    # Parameter setter configuration.
    set:
      signature: [value: {type: int}]
      instrument_command:
        - query: 'PARAMETER_3 {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'PARAMETER_3?'
