name: spectrum_analyzer

instrument:
  visa_sim: mock/visa/spectrum_analyzer/rs_fsw.yml
  address: TCPIP0::1.2.3.4::INSTR

topics:
  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    instrument_command: '{:}'
    type: set

  trigger_out:
    description: Sets the source of the reference frequency
    signature: [[], None]
    instrument_command: 'OUTP:TRIG2:PULS:IMM'
    type: set

  query_idn:
    description: Query the instrument identification
    signature: [[], str]
    instrument_command: '*IDN?'
    type: get

  tc_query_trigger_in:
    description: Query the connection status to the instrument
    signature: [[int], bool]
    type: set

  tm_query_trigger_in:
    description: Query the instrument identification
    signature: [[], bool]
    type: get

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  query_trigger_in:
    # Set parameter initial value upon instrument initialization.
    initial_value: 1

    setter:
      tc_query_trigger_in:
    getter:
      tm_query_trigger_in: