name: spectrum_analyzer
visa-sim: mock/visa/spectrum_analyzer/rs_fsw.yml
address: TCPIP0::1.2.3.4::INSTR

topics:
  connect:
    description: Establish Connection with Digitizer

  disconnect:
    description: Close connection with Digitizer

  raw:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  trigger_out:
    description: Sets the source of the reference frequency
    signature: [[], None]
    command: 'OUTP:TRIG2:PULS:IMM'

  query_idn:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  tc_query_trigger_in:
    description: Query the connection status to the instrument
    signature: [[int], bool]

  tm_query_trigger_in:
    description: Query the instrument identification
    signature: [[], bool]

  query_connected:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: 0
    setter:
      connect:
      disconnect:
    getter:
      query_connected:

  query_trigger_in:
    default: 1
    setter:
      tc_query_trigger_in:
    getter:
      tm_query_trigger_in: