############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

title: Mamba Server  # Main Window Title
background: artwork/app_background.png
load_screen:
  image: artwork/mamba_loading.png  # Pixmap Image
  time: 5  # Minimum time load image shall be shown