name: R&S SMB100B RF Signal Generator Controller
version: 0.1
status: Partial interface implementation
maintainer: Mamba Developers
maintainer_email: mambaframework@gmail.com

instrument:
  visa_sim: mock/visa/signal_generator/rs_smb100b.yml
  address: TCPIP0::1.2.3.4::INSTR

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  raw_query:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    # Set parameter description.
    description: Raw query to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_query: {type: str}]
      instrument_command:
        - query: '{:}'

    # Parameter getter configuration.
    get:

  raw_write:
    # Set parameter description.
    description: Raw write to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_write: {type: str}]
      instrument_command: [write: '{:}']

  idn:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'

  clear:
    # Set parameter description.
    description: Clear status

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*CLS']

  reset:
    # Set parameter description.
    description: Reset

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*RST']

  sys_err:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Oldest error in queue

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SYST:ERR?'

  power_level:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: RF level applied to the device under tests

    # Parameter setter configuration.
    set:
      signature: [amplitude: {type: float}]
      instrument_command:
        - write: 'POWer {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'POWer?'

  frequency_mode:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Frequency mode for generating the RF output signal

    # Parameter setter configuration.
    set:
      signature:
        - mode:
            type: str
            valid: ['CW', 'FIXed', 'SWEep', 'LIST']

      instrument_command:
        - write: 'FREQuency:MODE {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'FREQuency:MODE?'

  output_power:
    # Set parameter type.
    type: int

    # Set parameter description.
    description: RF output signal active status

    # Parameter setter configuration.
    set:
      signature:
        - state:
            type: int
            valid: [0, 1]

      instrument_command:
        - write: 'OUTP {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'OUTP?'

  cw_frequency:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: RF output CW frequency

    # Parameter setter configuration.
    set:
      signature: [fixed: {type: float}]
      instrument_command:
        - write: 'FREQuency:CW {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'FREQuency:CW?'

  clock_source:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Source of the reference frequency

    # Parameter setter configuration.
    set:
      signature:
        - state:
            type: str
            valid: ['INTernal', 'EXTernal']
      instrument_command:
        - write: 'SOURce:ROSCillator:SOURce {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SOURce:ROSCillator:SOURce?'
