name: Flask Server Mock

# Component network configuration
instrument:
  address: 0.0.0.0
  port: 5000

# Component TMTC

parameters:
  property_1:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 1

  property_2:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '2'

  property_3:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 3