# Component name

name: flask_server_mock

# Component network configuration

port: 5000

# Component TMTC

device:
    properties:
        property_1:
          default: 1
        property_2:
          default: '2'
        property_3:
          default: 3