################################################################################################
##
##  Copyright (c) Mamba Developers. All rights reserved.
##  Licensed under the MIT License. See License.txt in the project root for license information.
##
################################################################################################

name: Flask Server Mock

# Component network configuration
instrument:
  address: 0.0.0.0
  port: 5000

# Component TMTC

parameters:
  idn:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: 'Mamba Framework,HTTP Flask Mock,1.0'

    # Set parameter description.
    description: Instrument identification

  syst_err:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '0,_No_Error'

    # Set parameter description.
    description: Oldest error in queue

  cls:
    # Set parameter description.
    description: Clear status

  parameter_1:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 1

  parameter_2:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '2'

  parameter_3:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 3