############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

name: Save View  # Name of the action
menu: View  # High level Menu name shown in the menu bar