name: XMLRPC Mock

# Component network configuration

instrument:
  address: 0.0.0.0
  port: 8090

# Component TMTC

parameters:
  telemetry_1:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 1

  telemetry_2:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: '2'

  telemetry_3:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 3