name: m8131a
visa-sim: mock/visa/digitizer/ks_m8131a.yml
resource-name: TCPIP0::1.2.3.4::INSTR

topics:
  DIGITIZER_CONNECT:
    key: '@connect'
    description: Establish Connection with Digitizer

  DIGITIZER_DISCONNECT:
    key: '@disconnect'
    description: Close connection with Digitizer

  DIGITIZER_RAW:
    description: Send a raw command to the instrument
    signature: [[str], None]
    command: '{:}'

  DIGITIZER_CLOCK_SRC:
    description: Sets the source of the reference frequency
    signature: [[str], None]
    command: ':TIMebase:REFClock {:}'

  DIGITIZER_TC_QUERY_RAW:
    description: Perform raw query to the instrument
    signature: [[str], str]
    command: '{:}'

  DIGITIZER_QUERY_IDN:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  DIGITIZER_QUERY_CLOCK_SRC:
    description: Query the source of the reference frequency
    signature: [[], str]
    command: ':TIMebase:REFClock?'

  DIGITIZER_TM_QUERY_RAW:
    description: Retrieve the value of the last raw query
    signature: [[], str]
    command: '{:}'

  DIGITIZER_QUERY_CONNECTED:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: false
    setter:
      DIGITIZER_CONNECT:
      DIGITIZER_DISCONNECT:
    getter:
      DIGITIZER_QUERY_CONNECTED:

  query_raw_result:
    default: ''
    setter:
      DIGITIZER_TC_QUERY_RAW:
    getter:
      DIGITIZER_TM_QUERY_RAW: