name: SWITCH_Z2091C
visa-sim: mock/visa/switch_matrix/ks_z2091c.yml
address: TCPIP0::1.2.3.4::INSTR

topics:
  CONNECT:
    description: Establish Connection with Switch Matrix

  DISCONNECT:
    description: Close connection with Switch Matrix

  RAW:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  RST:
    description: Clear status
    command: '*CLS'

  QUERY_SYS_ERR:
    description: Query reads and clears one error.
    signature: [[], str]
    command: 'SYST:ERR?'

  TC_QUERY_RAW:
    description: Perform msg query to the instrument
    signature: [[str], str]
    command: '{:}'

  TM_QUERY_RAW:
    description: Retrieve the value of the last msg query
    signature: [[], str]
    command: '{:}'

  QUERY_IDN:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  QUERY_CONNECTED:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: 0
    setter:
      CONNECT:
      DISCONNECT:
    getter:
      QUERY_CONNECTED:

  query_raw_result:
    default: ''
    setter:
      TC_QUERY_RAW:
    getter:
      TM_QUERY_RAW: