################################################################################################
##
##  Copyright (c) Mamba Developers. All rights reserved.
##  Licensed under the MIT License. See License.txt in the project root for license information.
##
################################################################################################

name: New Project  # Name of the action
menu: '&File'  # High level Menu name shown in the menu bar
shortcut: Ctrl+N # Menu shortcut (Optional)