name: Keysight Series N5700 DC Power Supply Controller
version: 0.1
status: Partial interface implementation
maintainer: Mamba Developers
maintainer_email: mambaframework@gmail.com

instrument:
  visa_sim: mock/visa/power_supply/ks_n5700.yml
  address: TCPIP0::1.2.3.4::INSTR
  terminator:
    write: "\n"

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

  raw_query:
    # Set parameter type.
    type: str

    # Set parameter initial value upon instrument initialization.
    initial_value: ''

    # Set parameter description.
    description: Raw query to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_query: {type: str}]
      instrument_command:
        - query: '{:}'

    # Parameter getter configuration.
    get:

  raw_write:
    # Set parameter description.
    description: Raw write to intrument

    # Parameter setter configuration.
    set:
      signature: [raw_write: {type: str}]
      instrument_command: [write: '{:}']

  idn:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Instrument identification

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: '*IDN?'

  clear:
    # Set parameter description.
    description: Clear status

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*CLS']

  reset:
    # Set parameter description.
    description: Reset

    # Parameter setter configuration.
    set:
      instrument_command: [write: '*RST']

  sys_err:
    # Set parameter type.
    type: str

    # Set parameter description.
    description: Oldest error in queue

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'SYST:ERR?'

  output_current_setting:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: Output current setting

    # Parameter setter configuration.
    set:
      # Setter function signature.
      signature: [amperes: {type: float}]
      instrument_command:
        - write: 'CURR {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'CURR?'

  output_voltage_setting:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: Output voltage setting

    # Parameter setter configuration.
    set:
      # Setter function signature.
      signature: [volts: {type: float}]
      instrument_command:
        - write: 'VOLT {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'VOLT?'

  output_state:
    # Set parameter type.
    type: int

    # Set parameter description.
    description: Output enabled status

    # Parameter setter configuration.
    set:
      # Setter function signature.
      signature:
        - state:
            type: int
            valid: [0, 1]
      instrument_command:
        - write: 'OUTP {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'OUTP?'

  over_voltage_setting:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: Over-voltage trip point

    # Parameter setter configuration.
    set:
      # Setter function signature.
      signature: [volts: {type: float}]
      instrument_command:
        - write: 'VOLT:PROT:LEV {:}'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'VOLT:PROT:LEV?'

  measure_output_current:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: Measured output current

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'MEAS:CURR?'

  measure_output_voltage:
    # Set parameter type.
    type: float

    # Set parameter description.
    description: Measured output voltage

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'MEAS:VOLT?'
