################################################################################################
##
##  Copyright (c) Mamba Developers. All rights reserved.
##  Licensed under the MIT License. See License.txt in the project root for license information.
##
################################################################################################

name: '&About' # Name of the action
menu: '&Help' # High level Menu name shown in the menu bar
status_tip: Show the application's About box # Message shown in the status bar (Optional)
message_box_title: About Mamba Server # Top message box title (Optional)