name: spectrum_analyzer
visa-sim: mock/visa/spectrum_analyzer/rs_fsw.yml
resource-name: TCPIP0::1.2.3.4::INSTR

topics:
  FSW_CONNECT:
    key: '@connect'
    description: Establish Connection with Digitizer

  FSW_DISCONNECT:
    key: '@disconnect'
    description: Close connection with Digitizer

  FSW_RAW:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  FSW_TRIGGER_OUT:
    description: Sets the source of the reference frequency
    signature: [[], None]
    command: 'OUTP:TRIG2:PULS:IMM'

  FSW_QUERY_IDN:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  FSW_TC_QUERY_TRIGGER_IN:
    description: Query the connection status to the instrument
    signature: [[int], bool]

  FSW_TM_QUERY_TRIGGER_IN:
    description: Query the instrument identification
    signature: [[], bool]

  FSW_QUERY_CONNECTED:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: false
    setter:
      FSW_CONNECT:
      FSW_DISCONNECT:
    getter:
      FSW_QUERY_CONNECTED:

  query_trigger_in:
    default: 1
    setter:
      FSW_TC_QUERY_TRIGGER_IN:
    getter:
      FSW_TM_QUERY_TRIGGER_IN: