name: Single Port UDP Server Mock

# Component network configuration

instrument:
  address: 0.0.0.0
  port: 8087
  terminator:
    write: ''
    read: ''

# Component TMTC

parameters:
  raw_msg:
    # Parameter setter configuration.
    set:
      signature: [bytes_msg: {type: bytes}]