# Component name

name: cyclic_tcp_mock

# Component network configuration

host: 0.0.0.0
tc_port: 8081
tm_port: 8082

# Component TMTC

device:
    eom:
      TCPIP INSTR:
        q: "\r\n"
        r: "\n"

    properties:
        tm_1:
          default: 1
        tm_2:
          default: '2'
        tm_3:
          default: 3