name: switch_matrix
visa-sim: mock/visa/switch_matrix/ks_34980a.yml
address: TCPIP0::1.2.3.4::INSTR

device:
  encoding: utf-8
  eom:
    write: "\n"
    read: "\n"

topics:
  SWITCH_34980A_CONNECT:
    key: '@connect'
    description: Establish Connection with Switch Matrix

  SWITCH_34980A_DISCONNECT:
    key: '@disconnect'
    description: Close connection with Switch Matrix

  SWITCH_34980A_RAW:
    description: Send a msg command to the instrument
    signature: [[str], None]
    command: '{:}'

  SWITCH_34980A_RST:
    description: Clear status
    command: '*CLS'

  SWITCH_34980A_ROUT_CLOSE:
    description: Close channel
    signature: [[channel_id], None]
    command: 'ROUT:CLOS {:}'

  SWITCH_34980A_ROUT_OPEN:
    description: Open channel
    signature: [[channel_id], None]
    command: 'ROUT:OPEN {:}'

  SWITCH_34980A_ROUT_OPEN_ALL:
    description: Open all channels
    signature: [[slot_id], None]
    command: 'ROUT:OPEN:ALL {:}'

  SWITCH_34980A_INIT:
    description: Initiate the scan
    command: 'INIT'

  SWITCH_34980A_CONF_VOLT:
    description: Configure channel for DC voltage measurements
    signature: [[str], None]
    command: 'CONF:VOLT:DC {:}'

  SWITCH_34980A_CONF_SCAN:
    description: Configure scan list
    signature: [[str], None]
    command: 'ROUT:SCAN {:}'

  SWITCH_34980A_TRACE_ON:
    description: Enable channel trace output mode
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:ENAB ON, {:}'

  SWITCH_34980A_TRACE_OFF:
    description: Disable channel trace output mode
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:ENAB OFF, {:}'

  SWITCH_34980A_OUTP_ON:
    description: Enable channel output
    signature: [[channel_id], None]
    command: 'OUTP:STAT ON, {:}'

  SWITCH_34980A_OUTP_OFF:
    description: Disable channel output
    signature: [[channel_id], None]
    command: 'OUTP:STAT OFF, {:}'

  SWITCH_34980A_VOLT_OFFS:
    description: Configure channel voltage offset
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:VOLT:OFFS {:}'

  SWITCH_34980A_VOLT_GAIN:
    description: Configure channel voltage gain
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:VOLT:GAIN {:}'

  SWITCH_34980A_TRACE_NCYC:
    description: Configure channel trace cycle count
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:TRAC:NCYC {:}'

  SWITCH_34980A_TRACE_FUNC:
    description: Configure channel trace function
    signature: [[config], None]
    command: 'TRAC:FUNC {:}'

  SWITCH_34980A_TRACE:
    description: Apply trace to channel
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:TRAC {:}'

  SWITCH_34980A_FREQ:
    description: Configure channel frequency
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:FREQ {:}'

  SWITCH_34980A_QUERY_SYS_ERR:
    description: Query the error queue for the oldest item and removes it from the queue
    signature: [[], str]
    command: 'SYST:ERR?'

  SWITCH_34980A_TC_QUERY_RAW:
    description: Perform msg query to the instrument
    signature: [[str], str]
    command: '{:}'

  SWITCH_34980A_QUERY_IDN:
    description: Query the instrument identification
    signature: [[], str]
    command: '*IDN?'

  SWITCH_34980A_QUERY_ROUT_CLOSE:
    description: Query close state of the channel
    signature: [[channel_id], bool]
    command: 'ROUT:CLOS? {:}'

  SWITCH_34980A_QUERY_ROUT_OPEN:
    description: Query open state of the channel
    signature: [[channel_id], bool]
    command: 'ROUT:OPEN? {:}'

  SWITCH_34980A_QUERY_FETCH:
    description: Query stored readings from memory
    signature: [[], str]
    command: 'FETCh?'

  SWITCH_34980A_QUERY_VOLT_MEAS:
    description: Query open state of the channel
    signature: [[str], volt]
    command: 'MEASure:VOLTage:DC? {:}'

  SWITCH_34980A_QUERY_CHANNEL_RES:
    description: Query channel resistance
    signature: [[str], ohm]
    command: 'MEAS:RES? {:}'

  SWITCH_34980A_QUERY_TRACE:
    description: Query the trace output mode
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:ENAB? {:}'

  SWITCH_34980A_TM_QUERY_RAW:
    description: Retrieve the value of the last msg query
    signature: [[], str]
    command: '{:}'


  SWITCH_34980A_QUERY_FREQ:
    description: Query channel frequency
    signature: [[channel_id], None]
    command: 'SOUR:FUNC:FREQ? {:}'

  SWITCH_34980A_QUERY_CONNECTED:
    description: Query the connection status to the instrument
    signature: [[], bool]

parameters:
  connected:
    default: false
    setter:
      SWITCH_34980A_CONNECT:
      SWITCH_34980A_DISCONNECT:
    getter:
      SWITCH_34980A_QUERY_CONNECTED:
  query_raw_result:
    default: ''
    setter:
      SWITCH_34980A_TC_QUERY_RAW:
    getter:
      SWITCH_34980A_TM_QUERY_RAW: