############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

name: Script Controller
version: 0.1
status: Partial interface implementation
maintainer: Mamba Developers
maintainer_email: mamba.framework@gmail.com

instrument:
  address: None
  port: 0

parameters:
  cwd:
    # Set parameter type.
    type: str

    # Parameter setter configuration.
    set:
      signature: [path: {type: str}]
      instrument_command:
        - write: 'os.chdir("{:}")'

    # Parameter getter configuration.
    get:
      instrument_command:
        - query: 'os.getcwd()'

  bash_cmd:
    # Set parameter type.
    type: str

    # Parameter setter configuration.
    set:
      signature: [cmd: {type: str}]
      instrument_command:
        - bash_script: '{:}'

    # Parameter getter configuration.
    get:

  python_cmd:
    # Set parameter type.
    type: str

    # Parameter setter configuration.
    set:
      signature: [cmd: {type: str}]
      instrument_command:
        - python_script: '{:}'

    # Parameter getter configuration.
    get:
