############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

name: 'Custom Gui Component' # Name of the action
menu: 'Custom Menu' # High level Menu name shown in the menu bar