version: '0.1'
services:
  # Main window
  main_tk:
    title: Mi App

  # Main window plugins
  quit:
  about_tk:

  # Utilities
  logger:

  # Networking
  socket_server:
  hvs_socket_tmtc:

  # Central controller
  hvs_controller:

  # IO Controllers
  shutdown:
  smb: