name: Example of Cyclic TCP Telemetry Controller

instrument:
  address: 0.0.0.0
  port:
    tc: 8081
    tm: 8082
  encoding: utf-8
  terminator:
    write: "\r\n"
    read: "\n"

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to TCP server

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:






#topics:
#  TCP_SOCKET_CONTROLLER_CONNECT:
#    key: '@connect'
#    description: Establish Connection with remote cyclic tm server
#
#  TCP_SOCKET_CONTROLLER_DISCONNECT:
#    key: '@disconnect'
#    description: Close connection with remote cyclic tm  server
#
#  TCP_SOCKET_CONTROLLER_TC_TM_1:
#    description: Send a tm_1 set value
#    signature: [[str], None]
#    command: 'tm_1 {:}'
#
#  TCP_SOCKET_CONTROLLER_TC_TM_2:
#    description: Send a tm_1 set value
#    signature: [[str], None]
#    command: 'tm_2 {:}'
#
#  TCP_SOCKET_CONTROLLER_TC_TM_3:
#    description: Send a tm_1 set value
#    signature: [[str], None]
#    command: 'tm_3 {:}'
#
#  TCP_SOCKET_CONTROLLER_TM_TM_1:
#    description: Query the source of the reference frequency
#    signature: [[], str]
#
#  TCP_SOCKET_CONTROLLER_TM_TM_2:
#    description: Query the source of the reference frequency
#    signature: [[], str]
#
#  TCP_SOCKET_CONTROLLER_TM_TM_3:
#    description: Query the source of the reference frequency
#    signature: [[], str]
#
#  TCP_SOCKET_CONTROLLER_QUERY_CONNECTED:
#    description: Query the connection status to the instrument
#    signature: [[], bool]
#
#parameters:
#  connected:
#    default: 0
#    setter:
#      TCP_SOCKET_CONTROLLER_CONNECT:
#      TCP_SOCKET_CONTROLLER_DISCONNECT:
#    getter:
#      TCP_SOCKET_CONTROLLER_QUERY_CONNECTED:
#
#  tm_1:
#    default: ''
#    setter:
#      TCP_SOCKET_CONTROLLER_TC_TM_1:
#    getter:
#      TCP_SOCKET_CONTROLLER_TM_TM_1:
#
#  tm_2:
#    default: ''
#    setter:
#      TCP_SOCKET_CONTROLLER_TC_TM_2:
#    getter:
#      TCP_SOCKET_CONTROLLER_TM_TM_2:
#
#  tm_3:
#    default: ''
#    setter:
#      TCP_SOCKET_CONTROLLER_TC_TM_3:
#    getter:
#      TCP_SOCKET_CONTROLLER_TM_TM_3: