name: ks_33502a

instrument:
  visa_sim: mock/visa/amplifier/ks_33502a.yml
  address: TCPIP0::1.2.3.4::INSTR

topics:
  AMP_TC_1_AMP':
    signature: [[str], None]
    instrument_command: 'ROUT1:PATH {:}'
    type: set

  AMP_TC_2_AMP':
    signature: [[str], None]
    instrument_command: 'ROUT2:PATH {:}'
    type: set

  AMP_TC_1_OUTP':
    signature: [[str], None]
    instrument_command: 'OUTP1 {:}'
    type: set

  AMP_TC_2_OUTP':
    signature: [[str], None]
    instrument_command: 'OUTP2 {:}'
    type: set

  AMP_TC_1_COUP':
    signature: [[str], None]
    instrument_command: 'INP1:COUP {:}'
    type: set

  AMP_TC_2_COUP':
    signature: [[str], None]
    instrument_command: 'INP2:COUP {:}'
    type: set

  AMP_TC_1_IMP':
    signature: [[str], None]
    instrument_command: 'INP1:IMP {:}'
    type: set

  AMP_TC_2_IMP':
    signature: [[str], None]
    instrument_command: 'INP2:IMP {:}'
    type: set

parameters:
  connected:
    # Set parameter type.
    type: int

    # Set parameter initial value upon instrument initialization.
    initial_value: 0

    # Set parameter description.
    description: Connection status to instrument

    # Parameter setter configuration.
    set:
      # Alias allows to access parameter under another name.
      # Connect is an special ID, to command connect/disconnect from the equipment.
      alias: connect
      # Setter function signature.
      signature:
        - connect:
            type: int
            valid: [0, 1]

    # Parameter getter configuration.
    get:

