name: HVS H8823 Spacewire Ethernet Gateway Spw Raw Mock

# Component network configuration

instrument:
  address: 0.0.0.0
  port: 5001
  encoding: utf-8
  terminator:
    write: "\n"
    read: "\n"

# Component TMTC

parameters:
  raw_msg:
    # Parameter setter configuration.
    set:
      signature: [hex_msg: {type: str}]  # Trick: If first char is 0 then is a write, else is a query

