name: smb100b
visa-sim: simulator/rf_signal_generator/rs_smb100b.yaml
resource-name: TCPIP0::1.2.3.4::INSTR

topics:
  SMB_CONNECT:
    key: '@connect'
    description: Establish Connection with SMB

  SMB_DISCONNECT:
    key: '@disconnect'
    description: Close connection with SMB

  SMB_RST:
    description: Clear the output buffer
    command: '*CLS'

  SMB_RAW:
    description: Send a raw command to the instrument
    signature: [String]
    command: '{:}'

  SMB_FREQ_MODE:
    description: Set the frequency mode for generating the RF output signal
    signature: [String]
    command: 'FREQuency:MODE {:}'

  SMB_OUT_POWER:
    description: Set the RF output signal
    signature: [String]
    command: 'OUTP {:}'

  SMB_CW_FREQ:
    description: Sets the frequency of the RF output signal
    signature: [Int]
    command: 'FREQuency:CW {:}'

  SMB_CLOCK_SRC:
    description: Sets the source of the reference frequency
    signature: [String]
    command: 'SOURce:ROSCillator:SOURce {:}'

  SMB_POWER_LEVEL:
    description: Sets the RF level applied to the device under tests
    signature: [Float]
    command: 'POWer {:}'

  SMB_TC_QUERY_RAW:
    description: Perform raw query to the instrument
    signature: [String]
    return_type: String
    command: '{:}'

  SMB_QUERY_IDN:
    description: Query the instrument identification
    return_type: String
    command: '*IDN?'

  SMB_QUERY_OUT_POWER:
    description: Query the RF output signal
    return_type: Int
    command: 'OUTP?'

  SMB_QUERY_FREQ_MODE:
    description: Query the frequency mode for generating the RF output signal
    return_type: String
    command: 'FREQuency:MODE?'

  SMB_QUERY_CW_FREQ:
    description: Query the frequency of the RF output signal
    return_type: Int
    command: 'FREQuency:CW?'

  SMB_QUERY_CLOCK_SRC:
    description: Query the source of the reference frequency
    return_type: String
    command: 'SOURce:ROSCillator:SOURce?'

  SMB_QUERY_POWER_LEVEL:
    description: Query the RF level applied to the device under tests
    return_type: Float
    command: 'POWer?'

  SMB_TM_QUERY_RAW:
    description: Retrieve the value of the last raw query
    return_type: String
    command: '{:}'

  SMB_QUERY_CONNECTED:
    description: Query the connection status to the instrument
    return_type: Bool

parameters:
  connected:
    default: false
    setter:
      SMB_CONNECT:
      SMB_DISCONNECT:
    getter:
      SMB_QUERY_CONNECTED:

  query_raw_result:
    default: ''
    setter:
      SMB_TC_QUERY_RAW:
    getter:
      SMB_TM_QUERY_RAW: