############################################################################
#
# Copyright (c) Mamba Developers. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
############################################################################

name: HVS H8823 Spacewire Ethernet Gateway Spw Rmap Mock
version: 0.1
status: Template
maintainer: Mamba Developers
maintainer_email: mamba.framework@gmail.com

# Component network configuration

instrument:
  address: 0.0.0.0
  port: 5002

# Component TMTC

parameters:
  raw_msg:
    # Parameter setter configuration.
    set:
      signature: [bytes_msg: {type: bytes}]

